language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
script: mocha
deploy:
  provider: heroku
  api_key:
    secure: VrQq+6KvAxpNtXeOLRIsVhE3P+69sdlWJTSct9IbSNa7In/iYEAlTquGHREnNUimlk24HO5IzY9/aGMCZyqM/wZH8OWoFGUXidY3mBf4gXAFExE2BjAUpdkAeI0JuaMEFn/89hzlYScsaLWC2zxuuhdInC4TDIBoLcQia30a0YbFa+2usB5nJUrNm1P41TXNOLP5ztDXdlm3hGY9wO/IHKmb5Qf4DFmE/9JIu4DFz/IwoxqONuql9KJRfpH4v8qVZhpcI6sp3DgS3kvtm4WXFMK0brH9rSw+5uP5jq+tt3aQ3vAvYxK1ctxjhkLgJBQB47ad96R0hVLBHO57fpLbs0+iZPq2yFpqixmtawLcuKRBK7HYdLPCYXXQ4gKIsO0RyWrRQZWtBw0M5m6CkwZWxSKGXL80f6PdJpZ/+rnQqYRQ86TvpyaR4rcsCiaNraGeZ91Kv+Hbbvs4TSx6/BFK+K/8jQ6LYCeeME4aiX3SYAqPV/v7gfSot8T7twTNd6g6MBkueLvgJx0N98OSsredE+OIJsiCHFm98RhUSMNOvQYpFCLBCz0fwT6KOXddr81iUFg6KanNk7C9zP0OI4HfqJm149Y4SZJ7nvbpvtRKvDFMj6YKSm4B2C6wd9GfeYLMvQ8jzvmDz4QqBIX+KqwzUOShjmek6x3TeWKSR2uhjB4=
  app: polar-harbor-8077
  on:
    repo: ErikAbrahamson/travis-exercise
