language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
script:
- mocha
deploy:
  provider: heroku
  api_key:
    secure: "ARQRLNgOCeovFfoWoAO1SIwDY+Uxkt7fSxAFbv7thY92cEkUy3zVgHe6gVt2HXmIqJhAVFzgMmcaW3J6eoO4SE9Ig5W0vQNq7iXPLYmIdRNjyoSIOXEu0tfJqywrYC38TBYbb1zlOE71s8+mFafKdJsY/aeVkZVhfDCRm76Pvz/LgYUft9R0uWohnLAOs3b9pOZtAuflaJmYh2a2xsStYXx5sdSvQQRgNV27s7nrlg2ejIGGd21S3mgp3mFanz45GbiBV85T0wwQZcWeI4NUM4REAPUhJIUpCqjQVdeUdMMYUfs8S2APVDSuAhnaBpjhFLw9HVhfDgDqfU77qdutimb4NMSvkdCINjtuc2n5eGKBVv82yraUZgkHiqYb3TydPMpkAaW+xfKuswe2XhhNMExbCFZuS8BXMZmlamah47HLAR6zHxlBeb2KVauj8d6miIyVagQ+GzeJANGr1PlCgqe67HQ40qUofitNC0asFPyX1GjucuNvSqwEnRXIbpjGqA8sfz+nWNK24In4vDl8pHlaqNKX2cKuShR3go+LC2CzgoyjKMuWY9ZYAxmLtMj6ykNtwJsES9yQ1rfOffm4qhKynPADtBeMw3ViBV/mOLSShaWhTf0ly6vx17FfAc+rOAqs3LU4PU5/z3bsIAeovGonOpxDJHYNXK7f+ojm+PA="
  on:
    repo: ErikAbrahamson/travis-exercise
